name: Build iOS App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Missing Boost
      run: |
        cd Sudachi/Sudachi/Dependencies
        curl -L -o boost.tar.gz https://github.com/boostorg/boost/releases/download/boost-1.84.0/boost-1.84.0.tar.gz
        tar -xzf boost.tar.gz
        mv boost-1.84.0 boost
        rm boost.tar.gz
        ls -la

    - name: Build Xcode project
      run: |
        xcodebuild -project Pomelo.xcodeproj \
                   -scheme Pomelo \
                   -sdk iphoneos \
                   -configuration Release \
                   -derivedDataPath build \
                   CODE_SIGNING_ALLOWED=NO \
                   CODE_SIGNING_REQUIRED=NO \
                   CODE_SIGN_IDENTITY="" \
                   build

    - name: Package into .ipa
      run: |
        mkdir -p Payload
        APP_PATH=$(find build -name "*.app" -type d | head -n 1)
        cp -r "$APP_PATH" Payload/
        zip -r MeloZu.ipa Payload/
        rm -rf Payload

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MeloZu-ipa
        path: MeloZu.ipa
        retention-days: 5